// Generated by a large language model with updated artist and image information.

final List<Map<String, String>> allSongs = [
  {
    "title": "BIRDS OF A FEATHER",
    "artist": "Billie Eilish",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.4WsdifWr7nxNZi8lq_vYYwHaHa?pid=Api&P=0&h=180",
    "path": "1.mp3",
    "genre": "Pop",
  },
  {
    "title": "2 Be Loved (Am I Ready)",
    "artist": "Lizzo",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.g6Gw23ZlPOJG4GTXMBweKAHaEK?pid=Api&P=0&h=180",
    "path": "2 Be Loved (Am I Ready).mp3",
    "genre": "Pop",
  },
  {
    "title": "30 For 30 (with Kendrick Lamar)",
    "artist": "Drake",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.Hgy-K-_f5rPCHvXepNe8FgHaHa?pid=Api&P=0&h=180",
    "path": "30 For 30 (with Kendrick Lamar).mp3",
    "genre": "Hip-Hop",
  },

  {
    "title": "A Milli",
    "artist": "Lil Wayne",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.yjKmYJbrdv48I7Cp8kErdwHaHa?pid=Api&P=0&h=180",
    "path": "A Milli.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "A.D.H.D",
    "artist": "Kendrick Lamar",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.j1gpf6RaZYKV-8AtaP4YtQHaHa?pid=Api&P=0&h=180",
    "path": "A.D.H.D.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Aadat",
    "artist": "Talha Yunus",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.BG3Fv09SClqWPO5EazV2ywHaHa?pid=Api&P=0&h=180",
    "path": "Aadat.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Aaj Phir",
    "artist": "Arijit Singh",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.0jvWZOxmdhzkmPR10uiPogHaHa?pid=Api&P=0&h=180",
    "path": "Aaj Phir (From _Hate Story 2_).mp3",
    "genre": "Bollywood",
  },
  {
    "title": "Abaad",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "Abaad.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Aasan Nahin Yahan",
    "artist": "Arijit Singh",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.FM3O2lsbUkDbSjTx__02jAHaFj?pid=Api&P=0&h=180",
    "path": "Aasan Nahin Yahan (From _Aashiqui 2_).mp3",
    "genre": "Bollywood",
  },
  {
    "title": "About Damn Time",
    "artist": "Lizzo",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.q-VYy8wE80953cdst7EzmAHaHa?pid=Api&P=0&h=180",
    "path": "About Damn Time.mp3",
    "genre": "Pop",
  },
  {
    "title": "Addict",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "Addict.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Adore You",
    "artist": "Harry Styles",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.AjLaIfD2Rox3vDaP87H3AgHaHa?pid=Api&P=0&h=180",
    "path": "Adore You.mp3",
    "genre": "Pop",
  },
  {
    "title": "Afsanay",
    "artist": "Young Stunners",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.xL_o4jBm05TdtfvJ92HVtAHaHa?pid=Api&P=0&h=180",
    "path": "Afsanay.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "After Hours",
    "artist": "The Weeknd",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.8agTQGc0S7rSAHbJfsfkOAAAAA?pid=Api&P=0&h=180",
    "path": "After Hours.mp3",
    "genre": "R&B",
  },
  {
    "title": "Agar Tum Saath Ho",
    "artist": "Arijit Singh",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.hBiCWCKZY1YO3a37LegtSQHaHa?pid=Api&P=0&h=180",
    "path": "Agar Tum Saath Ho (From _Tamasha_).mp3",
    "genre": "Bollywood",
  },
  {
    "title": "Akela",
    "artist": "Divine",
    "image":
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4Ws5Ct_r-n381d3zz4vzNm_DpPqjCHUQyLg&s",
    "path": "Akela.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "all the good girls go to hell",
    "artist": "Billie Eilish",
    "image":
        "https://t2.genius.com/unsafe/344x344/https%3A%2F%2Fimages.genius.com%2F49fb176c8bb211930b6f26daed3f89ef.500x500x1.jpg",
    "path": "all the good girls go to hell.mp3",
    "genre": "Pop",
  },
  {
    "title": "All to Myself",
    "artist": "Dan + Shay",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.66FPdPf0rUYN2bwb-9z6iAHaHa?pid=Api&P=0&h=180",
    "path": "All to Myself.mp3",
    "genre": "Country",
  },
  {
    "title": "Alright",
    "artist": "Kendrick Lamar",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.H6ikkt0-iaxvKrOO4RKxIAHaHa?pid=Api&P=0&h=180",
    "path": "Alright.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Always Be My Fault",
    "artist": "The Weekend",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.VnzI8yCaNy6yQjk54iZvRwHaHa?pid=Api&P=0&h=180",
    "path": "Always Be My Fault.mp3",
    "genre": "R&B",
  },
  {
    "title": "Anjaan",
    "artist": "Jaani",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.nNQu9K5-MO6xH9Or1Q0MMQHaHH?pid=Api&P=0&h=180",
    "path": "Anjaan.mp3",
    "genre": "Punjabi Pop",
  },
  {
    "title": "As It Was",
    "artist": "Harry Styles",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.nepZnX8yVZcp7VBufd49-gHaHa?pid=Api&P=0&h=180",
    "path": "As It Was.mp3",
    "genre": "Pop",
  },
  {
    "title": "Baaton Ko Teri",
    "artist": "Arijit Singh",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.YraRN0IAQMJA-8h6FYtzjgHaHa?pid=Api&P=0&h=180",
    "path": "Baaton Ko Teri (From _All Is Well_).mp3",
    "genre": "Bollywood",
  },
  {
    "title": "BACKD00R",
    "artist": "Jhené Aiko",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.uXdg6U7aM-zm2UAw4Pk9iQHaID?pid=Api&P=0&h=180",
    "path": "BACKD00R (feat. Kendrick Lamar & Jhené Aiko).mp3",
    "genre": "R&B",
  },
  {
    "title": "Bad Blood",
    "artist": "Taylor Swift",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.DXCdphMI9MKKgYd4F85MgQAAAA?pid=Api&P=0&h=180",
    "path": "Bad Blood (feat. Kendrick Lamar) (Taylor's Version).mp3",
    "genre": "Pop",
  },
  {
    "title": "bad guy",
    "artist": "Billie Eilish",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.edP0ie0XzOywOF0W1p43cQHaHa?pid=Api&P=0&h=180",
    "path": "bad guy.mp3",
    "genre": "Pop",
  },
  {
    "title": "Bad Habits",
    "artist": "Ed Sheeran",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.5eRawwT3Z9dmdfbQaygP_gHaHa?pid=Api&P=0&h=180",
    "path": "Bad Habits.mp3",
    "genre": "Pop",
  },
  {
    "title": "Banda Down",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "Banda Down.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Barishein Chali Gayi",
    "artist": "Bella",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.msjKvEpOI1Fj4GVCumqXWAHaHa?pid=Api&P=0&h=180",
    "path": "Barishein Chali Gayi.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Barsaat",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "Barsaat.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Bas Jhut",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "Bas Jhut.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Bechara",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "Bechara.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "bellyache",
    "artist": "Billie Eilish",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pd9Q-p5N0twJ2Pu2avgtNAHaHa?pid=Api&P=0&h=180",
    "path": "bellyache.mp3",
    "genre": "Pop",
  },
  {
    "title": "Best Friend",
    "artist": "Saweetie",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.PJQzRedRBcCb6clVXDHNggHaJl?pid=Api&P=0&h=180",
    "path": "Best Friend (feat. Doja Cat).mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Big Pimpin'",
    "artist": "Jay-Z",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.2b5SqlxeKCjTnGysovHtegAAAA?pid=Api&P=0&h=180",
    "path": "Big Pimpin'.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Billie Bossa Nova",
    "artist": "Billie Eilish",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.e8yOGXMDF0phAQ-1dn2YSQHaHX?pid=Api&P=0&h=180",
    "path": "Billie Bossa Nova.mp3",
    "genre": "Pop",
  },
  {
    "title": "Bin Tere",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "Bin Tere.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "bitches broken hearts",
    "artist": "Billie Eilish",
    "image":
        "https://t2.genius.com/unsafe/344x344/https%3A%2F%2Fimages.genius.com%2Fabd7309daddeb451ecdd26f126c06b8a.1000x1000x1.png",
    "path": "bitches broken hearts.mp3",
    "genre": "R&B",
  },
  {
    "title": "BITTERSUITE",
    "artist": "Billie Eilish",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.l08mQULJxEaUgC97P58L0QHaHQ?pid=Api&P=0&h=180",
    "path": "BITTERSUITE.mp3",
    "genre": "Pop",
  },
  {
    "title": "Blinding Lights",
    "artist": "The Weeknd",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.aESN9ZbNP7ugzKm65zK3ZwHaHa?pid=Api&P=0&h=180",
    "path": "Blinding Lights.mp3",
    "genre": "Pop",
  },
  {
    "title": "BLUE",
    "artist": "Billie Eilish",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.cc8RicpnhAnkekQb-qOUcgHaHa?pid=Api&P=0&h=180",
    "path": "BLUE.mp3",
    "genre": "Pop",
  },
  {
    "title": "Bored",
    "artist": "Billie Eilish",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.bKf1TfFgPWb8Y8N_0Dxo7QAAAA?pid=Api&P=0&h=180",
    "path": "Bored.mp3",
    "genre": "Pop",
  },
  {
    "title": "BreakUp Call",
    "artist": "Bella",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.iumDQs7mZbTQXwp8EzNYywHaFj?pid=Api&P=0&h=180",
    "path": "BreakUp Call.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "bury a friend",
    "artist": "Billie Eilish",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.slMaSJQex4UIIxC5-S151wHaHa?pid=Api&P=0&h=180",
    "path": "bury a friend.mp3",
    "genre": "Pop",
  },
  {
    "title": "Call Out My Name",
    "artist": "The Weeknd",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.u_qMcgOn4FBBng8ZV5zTgwHaHa?pid=Api&P=0&h=180",
    "path": "Call Out My Name.mp3",
    "genre": "R&B",
  },
  {
    "title": "Can't Feel My Face",
    "artist": "The Weeknd",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.imTHgTFAR-W6u1RZNOOK-gHaHa?pid=Api&P=0&h=180",
    "path": "Can't Feel My Face.mp3",
    "genre": "Pop",
  },
  {
    "title": "Can't Hold Us",
    "artist": "Macklemore & Ryan Lewis",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.XFqnsDCO7E0e_WgSz4B0fAHaHa?pid=Api&P=0&h=180",
    "path": "Can't Hold Us (feat. Ray Dalton).mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Capital Rap",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "Capital Rap.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "CD",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "CD.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Celebrate",
    "artist": "Bella",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.qFOIp1peykEeSYhRCMfy0QHaFV?pid=Api&P=0&h=180",
    "path": "Celebrate.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Cha Chi",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "Cha Chi.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Chains & Whips",
    "artist": "Kendrick Lamar",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.NVeDamgSEASCqLuUNKHlzwHaHa?pid=Api&P=0&h=180",
    "path": "Chains & Whips.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Chal Wahan Jaate Hain",
    "artist": "Arijit Singh",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.J2HfuwtGWVB1BFPnIWxuAAHaHa?pid=Api&P=0&h=180",
    "path": "Chal Wahan Jaate Hain (From _Chal Wahan Jaate Hain_).mp3",
    "genre": "Bollywood",
  },
  {
    "title": "Champion",
    "artist": "Bella",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.YDA1kn7cuBPR2JZ8amzpgAHaHa?pid=Api&P=0&h=180",
    "path": "Champion.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "CHIHIRO",
    "artist": "Billie Eilish",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.B8GPAbIe0SZsCEEasF0zhwHaEK?pid=Api&P=0&h=180",
    "path": "CHIHIRO.mp3",
    "genre": "Pop",
  },
  {
    "title": "Cold Heart (PNAU Remix)",
    "artist": "Elton John & Dua Lipa",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.ATJCEA26yg6jq5bfxOxUsQHaEK?pid=Api&P=0&h=180",
    "path": "Cold Heart - PNAU Remix.mp3",
    "genre": "Dance-Pop",
  },
  {
    "title": "Collard Greens",
    "artist": "ScHoolboy Q",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.K-WDlqF4QcX6EuVbMtUZ5wHaHa?pid=Api&P=0&h=180",
    "path": "Collard Greens.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Come & Go (with Marshmello)",
    "artist": "Juice WRLD",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP._6b-Pp2V70k0v9EVl06pmwHaHa?pid=Api&P=0&h=180",
    "path": "Come & Go (with Marshmello).mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Come Get Her",
    "artist": "Rae Sremmurd",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.YN79qrj0w8pnRJEMqsrDEAHaHa?pid=Api&P=0&h=180",
    "path": "Come Get Her.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "come out and play",
    "artist": "Billie Eilish",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.1XZsdW--gvBOKrZAdV2wjQHaHa?pid=Api&P=0&h=180",
    "path": "come out and play.mp3",
    "genre": "Pop",
  },
  {
    "title": "COPYCAT",
    "artist": "Billie Eilish",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.qQaJOjL_k84xeqvMMHJRlQHaHa?pid=Api&P=0&h=180",
    "path": "COPYCAT.mp3",
    "genre": "Pop",
  },
  {
    "title": "Count Me Out",
    "artist": "Kendrick Lamar",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.pslkdPsBG-GSEeN45wCPwgHaD4?pid=Api&P=0&h=180",
    "path": "Count Me Out.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Crack A Bottle",
    "artist": "Eminem, Dr. Dre & 50 Cent",
    "image":
        "https://t2.genius.com/unsafe/344x344/https%3A%2F%2Fimages.genius.com%2Fc7c668375776c76be99ffb3a7ae9d9dd.1000x1000x1.jpg",
    "path": "Crack A Bottle.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Crazy In Love",
    "artist": "Beyoncé",
    "image":
        "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Beyonce_-_Crazy_in_Love_%28single%29.png/250px-Beyonce_-_Crazy_in_Love_%28single%29.png",
    "path": "Crazy In Love (feat. JAY-Z).mp3",
    "genre": "R&B",
  },
  {
    "title": "Creepin'",
    "artist": "Metro Boomin",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.O2rLzbhkMAe8BLdoGzo_XAHaHa?pid=Api&P=0&h=180",
    "path": "Creepin' (with The Weeknd & 21 Savage).mp3",
    "genre": "R&B",
  },
  {
    "title": "Cruel Summer",
    "artist": "Taylor Swift",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.5Y3Acku98-bYiktMLiAjLQHaHa?pid=Api&P=0&h=180",
    "path": "Cruel Summer.mp3",
    "genre": "Pop",
  },
  {
    "title": "Cry For Me",
    "artist": "The Weeknd",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.LDGosH9v8N4IpHJmvXDWwQHaHa?pid=Api&P=0&h=180",
    "path": "Cry For Me.mp3",
    "genre": "R&B",
  },
  {
    "title": "CUFF IT",
    "artist": "Beyoncé",
    "image":
        "https://t2.genius.com/unsafe/344x344/https%3A%2F%2Fimages.genius.com%2F2a76ae7f7d284b6b408c855ffb1dc3ae.1000x1000x1.png",
    "path": "CUFF IT.mp3",
    "genre": "R&B",
  },
  {
    "title": "Dance The Night",
    "artist": "Dua Lipa",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.T20hV35NdlrAGHSX2bk8MgHaHa?pid=Api&P=0&h=180",
    "path": "Dance The Night - From Barbie The Album.mp3",
    "genre": "Pop",
  },
  {
    "title": "Dancing In The Flames",
    "artist": "The Weeknd",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.wKkcIFxpmUiMk1l1i3EoJwHaHa?pid=Api&P=0&h=180",
    "path": "Dancing In The Flames.mp3",
    "genre": "R&B",
  },
  {
    "title": "Dhoke",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "Dhoke.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Die For You (Remix)",
    "artist": "The Weeknd & Ariana Grande",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.CP61-cTyuTcgkGFqzdcKNQHaHd?pid=Api&P=0&h=180",
    "path": "Die For You - Remix.mp3",
    "genre": "R&B",
  },
  {
    "title": "Die For You",
    "artist": "The Weeknd",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.cYGetkZE2zhotlqODWmJjAHaHY?pid=Api&P=0&h=180",
    "path": "Die For You.mp3",
    "genre": "R&B",
  },
  {
    "title": "Die Hard",
    "artist": "Kendrick Lamar",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.rJ2tpnD7M1JlFzlURxi26QHaHa?pid=Api&P=0&h=180",
    "path": "Die Hard.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Dil Ke Paas",
    "artist": "Arijit Singh",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.T-jZNu03QORuLeoklOjqvwHaHZ?pid=Api&P=0&h=180",
    "path": "Dil Ke Paas (From _Wajah Tum Ho_).mp3",
    "genre": "Bollywood",
  },
  {
    "title": "Dil Se",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "Dil Se.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Dilliwaali Girlfriend",
    "artist": "Arijit Singh & Sunidhi Chauhan",
    "image":
        "https://upload.wikimedia.org/wikipedia/en/6/68/Dilliwaali_Girlfriend.jpg",
    "path": "Dilliwaali Girlfriend (From _Yeh Jawaani Hai Deewani_).mp3",
    "genre": "Bollywood",
  },
  {
    "title": "DL91 FM",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "DL91 FM.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "DNA.",
    "artist": "Kendrick Lamar",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.lpVc2jrigANJnjlItybp3AHaHa?pid=Api&P=0&h=180",
    "path": "DNA..mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "dodger blue",
    "artist": "Kendrick Lamar",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.qiPJQifv7r-QCEVCOskeTwHaHa?pid=Api&P=0&h=180",
    "path": "dodger blue (feat. wallie the sensei, siete7x, roddy ricch).mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Doja",
    "artist": "Central Cee",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.GRuXEpMm10c306rFBngBswAAAA?pid=Api&P=0&h=180",
    "path": "Doja.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Don't Start Now",
    "artist": "Dua Lipa",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.9mek0B-I6GMwY09fW4DwrAHaKt?pid=Api&P=0&h=180",
    "path": "Don't Start Now.mp3",
    "genre": "Pop",
  },
  {
    "title": "Double Fantasy",
    "artist": "The Weeknd",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.2vRe93f03Mvd5MLkGVeggQHaHa?pid=Api&P=0&h=180",
    "path": "Double Fantasy (with Future).mp3",
    "genre": "R&B",
  },
  {
    "title": "Doves In The Wind",
    "artist": "SZA",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.8K8Qyw4OiF5qiMPIlwFk8QHaHa?pid=Api&P=0&h=180",
    "path": "Doves In The Wind (feat. Kendrick Lamar).mp3",
    "genre": "R&B",
  },
  {
    "title": "Downers At Dusk",
    "artist": "Talha Anjum",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.xI8f2SH9F1rHiquppEaeWwHaEK?pid=Api&P=0&h=180",
    "path": "Downers At Dusk.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Duaa",
    "artist": "Arijit Singh & Nandini Srikar",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.4SSbydfMNx2Q9veLvYaRKQHaFj?pid=Api&P=0&h=180",
    "path": "Duaa (From _Shanghai_).mp3",
    "genre": "Bollywood",
  },
  {
    "title": "DUCKWORTH.",
    "artist": "Kendrick Lamar",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.iRHJ2_Ko7EC7kNeihuvZSgHaHa?pid=Api&P=0&h=180",
    "path": "DUCKWORTH..mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Earned It",
    "artist": "The Weeknd",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.6bcogDWVBOCAFa3aVOd89wHaHa?pid=Api&P=0&h=180",
    "path":
        "Earned It (Fifty Shades Of Grey) - From The _Fifty Shades Of Grey_ Soundtrack.mp3",
    "genre": "R&B",
  },
  {
    "title": "El Matador",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "El Matador.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Electricity",
    "artist": "Silk City & Dua Lipa",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.QB57OH9Krg800JWoAItExgHaHa?pid=Api&P=0&h=180",
    "path": "Electricity.mp3",
    "genre": "Dance-Pop",
  },
  {
    "title": "Encore",
    "artist": "Jay-Z",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.7P1kLlJcN9VVyMEQmjDWZwHaHa?pid=Api&P=0&h=180",
    "path": "Encore.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Energy",
    "artist": "Drake",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.IXAERG0oVjFJhUz11cpNgQHaKs?pid=Api&P=0&h=180",
    "path": "Energy.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Espresso",
    "artist": "Sabrina Carpenter",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.5Ovk9HoyOh10i4nufAdBtQHaEK?pid=Api&P=0&h=180",
    "path": "Espresso.mp3",
    "genre": "Pop",
  },
  {
    "title": "euphoria",
    "artist": "Kendrick Lamar",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.khcZx8DW9zaVWSpRIwKxLgHaEK?pid=Api&P=0&h=180",
    "path": "euphoria.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "everything i wanted",
    "artist": "Billie Eilish",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.5wkInKJU7s2zrG7SuRrh2wHaE8?pid=Api&P=0&h=180",
    "path": "everything i wanted.mp3",
    "genre": "Pop",
  },
  {
    "title": "False Idols",
    "artist": "The Weeknd",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.HAIm6CWl3h35hyCpc7F8nQHaHa?pid=Api&P=0&h=180",
    "path": "False Idols (with Lil Baby, Suzanna Son).mp3",
    "genre": "R&B",
  },
  {
    "title": "family ties",
    "artist": "Baby Keem",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.CODbLMHm42Me4xHKnd62TQHaHa?pid=Api&P=0&h=180",
    "path": "family ties (with Kendrick Lamar).mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Father Time (feat. Sampha)",
    "artist": "Kendrick Lamar",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.RjsDjfcfDA75dXawNnCZ0AAAAA?pid=Api&P=0&h=180",
    "path": "Father Time (feat. Sampha).mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "First Class",
    "artist": "Jack Harlow",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.A8zgdNc6Y9Az8k9khWvkiQHaHa?pid=Api&P=0&h=180",
    "path": "First Class.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Formation",
    "artist": "Beyoncé",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.KarISqVz5xqR0AC16yxeuAHaHa?pid=Api&P=0&h=180",
    "path": "Formation.mp3",
    "genre": "R&B",
  },
  {
    "title": "Gasoline",
    "artist": "The Weeknd",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.utqNnnBFo8wmxeQKeiLGIgHaEK?pid=Api&P=0&h=180",
    "path": "Gasoline.mp3",
    "genre": "Pop",
  },
  {
    "title": "Getting Older",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "Getting Older.mp3",
    "genre": "Pop",
  },
  {
    "title": "Glass Half Full",
    "artist": "Talha Anjum",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.pQgyu4PA6YHGRKzZ71eTNQHaHa?pid=Api&P=0&h=180",
    "path": "Glass Half Full.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Glorious (feat. Skylar Grey)",
    "artist": "Macklemore",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.Vn-TkekViga5BLbUC7kBbQHaHa?pid=Api&P=0&h=180",
    "path": "Glorious (feat. Skylar Grey).mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Good as Hell",
    "artist": "Lizzo",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.pYhaAQWnbq2OyjbCFTJnWQHaHa?pid=Api&P=0&h=180",
    "path": "Good as Hell.mp3",
    "genre": "Pop",
  },
  {
    "title": "GOOD CREDIT (with Kendrick Lamar)",
    "artist": "Unknown Artist",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.Yrf3CjEpddQTJpy59vafwwHaHa?pid=Api&P=0&h=180",
    "path": "GOOD CREDIT (with Kendrick Lamar).mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "greedy",
    "artist": "Tate McRae",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.oTYXWpHcR23u9HDFkB007gHaGB?pid=Api&P=0&h=180",
    "path": "greedy.mp3",
    "genre": "Pop",
  },
  {
    "title": "Guess",
    "artist": "Billie Eilish",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.IkYrVL-SYBub-07YDz7HBgHaD4?pid=Api&P=0&h=180",
    "path": "Guess featuring billie eilish.mp3",
    "genre": "Pop",
  },
  {
    "title": "Guldasta",
    "artist": "Seedhe Maut",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180",
    "path": "Guldasta.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "Hair Down",
    "artist": "Kendrick Lamar",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.ujWhwMdX8IP9TTgTyyJ-cgAAAA?pid=Api&P=0&h=180",
    "path": "Hair Down.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Halley's Comet",
    "artist": "Billie Eilish",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.bWb5e0jjip49KVOOXyMsrQHaD4?pid=Api&P=0&h=180",
    "path": "Halley's Comet.mp3",
    "genre": "Pop",
  },
  {
    "title": "Hallucinate",
    "artist": "Dua Lipa",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.dVv9AmtH1TvtaQ2LFm5GwQHaHa?pid=Api&P=0&h=180",
    "path": "Hallucinate.mp3",
    "genre": "Dance-Pop",
  },
  {
    "title": "Happier Than Ever",
    "artist": "Billie Eilish",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.5iYAU3ZRhrypx-e-oYqozQHaHa?pid=Api&P=0&h=180",
    "path": "Happier Than Ever.mp3",
    "genre": "Pop",
  },
  {
    "title": "Har Kisi Ko",
    "artist": "Nikhil D'Souza",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.cJvS5Q3GlSp-Ol3MI4tvDAHaEK?pid=Api&P=0&h=180",
    "path": "Har Kisi Ko (From _Boss_).mp3",
    "genre": "Bollywood",
  },
  {
    "title": "Head & Heart",
    "artist": "Joel Corry",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.4W5OFhTyEb0JPjPhM0LeqQHaHa?pid=Api&P=0&h=180",
    "path": "Head & Heart (feat. MNEK).mp3",
    "genre": "Dance-Pop",
  },
  {
    "title": "hey now",
    "artist": "Oasis",
    "image":
        "https://tse4.mm.bing.net/th/id/OIP.YlrumAUb7clb5M_cvclFXwHaHa?pid=Api&P=0&h=180",
    "path": "hey now (feat. dody6).mp3",
    "genre": "Rock",
  },
  {
    "title": "Higher Love",
    "artist": "Kygo & Whitney Houston",
    "image":
        "https://upload.wikimedia.org/wikipedia/en/thumb/3/3e/Steve_Winwood_-_Higher_Love.jpeg/250px-Steve_Winwood_-_Higher_Love.jpeg",
    "path": "Higher Love.mp3",
    "genre": "Dance-Pop",
  },
  {
    "title": "hostage",
    "artist": "Billie Eilish",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.wY_rWyyan1NCKXQxlQ7SjAHaEK?pid=Api&P=0&h=180",
    "path": "hostage.mp3",
    "genre": "Pop",
  },
  {
    "title": "Houdini",
    "artist": "Dua Lipa",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.bQmyEowZ6U1fM2AYqSGw-QHaEK?pid=Api&P=0&h=180",
    "path": "Houdini.mp3",
    "genre": "Pop",
  },
  {
    "title": "Hum Mar Jayenge",
    "artist": "Arijit Singh & Tulsi Kumar",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.tBDO2Yy5jMllJJhfl2wo7wHaEK?pid=Api&P=0&h=180",
    "path": "Hum Mar Jayenge (From _Aashiqui 2_).mp3",
    "genre": "Bollywood",
  },
  {
    "title": "Humble Poet",
    "artist": "Bella",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.vgAVvS9LrS1-lm_HIhEN5QHaHa?pid=Api&P=0&h=180",
    "path": "Humble Poet.mp3",
    "genre": "Desi Hip-Hop",
  },
  {
    "title": "HUMBLE.",
    "artist": "Kendrick Lamar",
    "image":
        "https://tse3.mm.bing.net/th/id/OIP.InITaBqp0LWu5fR6uVp2PQHaDt?pid=Api&P=0&h=180",
    "path": "HUMBLE..mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "Hypnotize",
    "artist": "The Notorious B.I.G.",
    "image":
        "https://tse2.mm.bing.net/th/id/OIP.gixVAYHUbi-R6R_JGXcFtwAAAA?pid=Api&P=0&h=180",
    "path": "Hypnotize - 2014 Remaster.mp3",
    "genre": "Hip-Hop",
  },
  {
    "title": "I Didn't Change My Number",
    "artist": "Billie Eilish",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.WtROFgzsejXVzOH7uRczUAHaEK?pid=Api&P=0&h=180",
    "path": "I Didn't Change My Number.mp3",
    "genre": "Pop",
  },
  {
    "title": "I Don't Care",
    "artist": "Ed Sheeran",
    "image":
        "https://tse1.mm.bing.net/th/id/OIP.ILAXV_WBba4k5NuV94oPqgHaHa?pid=Api&P=0&h=180",
    "path": "I Don't Care (with Justin Bieber).mp3",
    "genre": "Pop",
  },

  {
    "title": "I Feel It Coming",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "I Feel It Coming.mp3",
  },
  {
    "title": "I Like It",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "I Like It.mp3",
  },
  {
    "title": "i love you",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "i love you.mp3",
  },
  {
    "title": "I Was Never There",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "I Was Never There.mp3",
  },
  {
    "title": "i",
    "artist": "Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Kendrick+Lamar",
    "path": "i.mp3",
  },
  {
    "title": "idontwannabeyouanymore",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "idontwannabeyouanymore.mp3",
  },
  {
    "title": "Ilahi (From _Yeh Jawaani Hai Deewani_)",
    "artist": "Arijit Singh",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Ilahi (From _Yeh Jawaani Hai Deewani_).mp3",
  },
  {
    "title": "ilomilo",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "ilomilo.mp3",
  },
  {
    "title": "In Your Eyes",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "In Your Eyes.mp3",
  },
  {
    "title": "Into Your Arms (feat. Ava Max)",
    "artist": "Witt Lowry",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Witt+Lowry",
    "path": "Into Your Arms (feat. Ava Max).mp3",
  },
  {
    "title": "Ishq Mubarak (From _Tum Bin 2_)",
    "artist": "Arijit Singh",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Ishq Mubarak (From _Tum Bin 2_).mp3",
  },
  {
    "title": "Itni Si Baat Hain (From _Azhar_)",
    "artist": "Arijit Singh & Antara Mitra",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Itni Si Baat Hain (From _Azhar_).mp3",
  },
  {
    "title": "Juice",
    "artist": "Lizzo",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Lizzo",
    "path": "Juice.mp3",
  },
  {
    "title": "Just Wanna Rock",
    "artist": "Lil Uzi Vert",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Lil+Uzi+Vert",
    "path": "Just Wanna Rock.mp3",
  },
  {
    "title": "K-POP",
    "artist": "Travis Scott, Bad Bunny & The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "K-POP.mp3",
  },
  {
    "title": "Kabira (Encore) [From _Yeh Jawaani Hai Deewani_]",
    "artist": "Arijit Singh & Harshdeep Kaur",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Kabira (Encore) [From _Yeh Jawaani Hai Deewani_].mp3",
  },
  {
    "title": "Kalandar",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Kalandar.mp3",
  },
  {
    "title": "Kehne Do",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Kehne Do.mp3",
  },
  {
    "title": "Kilas",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Kilas.mp3",
  },
  {
    "title": "King Kunta",
    "artist": "Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Kendrick+Lamar",
    "path": "King Kunta.mp3",
  },
  {
    "title": "Kiss Me More (feat. SZA)",
    "artist": "Doja Cat",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Doja+Cat",
    "path": "Kiss Me More (feat. SZA).mp3",
  },
  {
    "title": "KTMN",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "KTMN.mp3",
  },
  {
    "title": "Late Night Talking",
    "artist": "Harry Styles",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Harry+Styles",
    "path": "Late Night Talking.mp3",
  },
  {
    "title": "Leave Before You Love Me (with Jonas Brothers)",
    "artist": "Marshmello & Jonas Brothers",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Marshmello",
    "path": "Leave Before You Love Me (with Jonas Brothers).mp3",
  },
  {
    "title": "Let You Down",
    "artist": "NF",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=NF",
    "path": "Let You Down.mp3",
  },
  {
    "title": "Levitating (feat. DaBaby)",
    "artist": "Dua Lipa",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Dua+Lipa",
    "path": "Levitating (feat. DaBaby).mp3",
  },
  {
    "title": "Like That (feat. Gucci Mane)",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Like That (feat. Gucci Mane).mp3",
  },
  {
    "title": "Like That",
    "artist": "Doja Cat",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Doja+Cat",
    "path": "Like That.mp3",
  },
  {
    "title": "Lose Yourself",
    "artist": "Eminem",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Eminem",
    "path": "Lose Yourself.mp3",
  },
  {
    "title": "Lost Cause",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "Lost Cause.mp3",
  },
  {
    "title": "Lost",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Lost.mp3",
  },
  {
    "title": "Love Me Harder",
    "artist": "Ariana Grande",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Ariana+Grande",
    "path": "Love Me Harder.mp3",
  },
  {
    "title": "LOVE. FEAT. ZACARI.",
    "artist": "Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Kendrick+Lamar",
    "path": "LOVE. FEAT. ZACARI..mp3",
  },
  {
    "title": "lovely (with Khalid)",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "lovely (with Khalid).mp3",
  },
  {
    "title": "LOYALTY. FEAT. RIHANNA.",
    "artist": "Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Kendrick+Lamar",
    "path": "LOYALTY. FEAT. RIHANNA..mp3",
  },
  {
    "title": "LUNCH",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "LUNCH.mp3",
  },
  {
    "title": "luther (with sza)",
    "artist": "Frank Ocean",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Frank+Ocean",
    "path": "luther (with sza).mp3",
  },
  {
    "title": "L’AMOUR DE MA VIE",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "L’AMOUR DE MA VIE.mp3",
  },
  {
    "title": "Maar Kaat",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Maar Kaat.mp3",
  },
  {
    "title": "Madira",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Madira.mp3",
  },
  {
    "title": "Male Fantasy",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "Male Fantasy.mp3",
  },
  {
    "title": "Mast Magan (From _2 States_)",
    "artist": "Arijit Singh & Chinmayi Sripaada",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Mast Magan (From _2 States_).mp3",
  },
  {
    "title": "Maut Ka Kua",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Maut Ka Kua.mp3",
  },
  {
    "title": "meet the grahams",
    "artist": "Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Kendrick+Lamar",
    "path": "meet the grahams.mp3",
  },
  {
    "title": "Milne Hai Mujhse Aayi (From _Aashiqui 2_)",
    "artist": "Arijit Singh",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Milne Hai Mujhse Aayi (From _Aashiqui 2_).mp3",
  },
  {
    "title": "Mona Lisa (feat. Kendrick Lamar)",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Mona Lisa (feat. Kendrick Lamar).mp3",
  },
  {
    "title": "Moth To A Flame (with The Weeknd)",
    "artist": "Swedish House Mafia",
    "image":
        "https://placehold.co/200x200/4A1F47/ffffff?text=Swedish+House+Mafia",
    "path": "Moth To A Flame (with The Weeknd).mp3",
  },
  {
    "title": "Motley Crew",
    "artist": "Post Malone",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Post+Malone",
    "path": "Motley Crew.mp3",
  },
  {
    "title": "MP3",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "MP3.mp3",
  },
  {
    "title": "Mud",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Mud.mp3",
  },
  {
    "title": "my boy",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "my boy.mp3",
  },
  {
    "title": "my future",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "my future.mp3",
  },
  {
    "title": "my strange addiction",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "my strange addiction.mp3",
  },
  {
    "title": "N95",
    "artist": "Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Kendrick+Lamar",
    "path": "N95.mp3",
  },
  {
    "title": "NDA",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "NDA.mp3",
  },
  {
    "title": "New Rules",
    "artist": "Dua Lipa",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Dua+Lipa",
    "path": "New Rules.mp3",
  },
  {
    "title": "No Lie",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "No Lie.mp3",
  },
  {
    "title": "No Other Place",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "No Other Place.mp3",
  },
  {
    "title": "No Time To Die",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "No Time To Die.mp3",
  },
  {
    "title": "Not Like Us",
    "artist": "Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Kendrick+Lamar",
    "path": "Not Like Us.mp3",
  },
  {
    "title": "Not My Responsibility",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "Not My Responsibility.mp3",
  },
  {
    "title": "ocean eyes",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "ocean eyes.mp3",
  },
  {
    "title": "One Kiss (with Dua Lipa)",
    "artist": "Calvin Harris",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Calvin+Harris",
    "path": "One Kiss (with Dua Lipa).mp3",
  },
  {
    "title": "One Of The Girls (with JENNIE, Lily Rose Depp)",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "One Of The Girls (with JENNIE, Lily Rose Depp).mp3",
  },
  {
    "title": "One Right Now (with The Weeknd)",
    "artist": "Post Malone",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Post+Malone",
    "path": "One Right Now (with The Weeknd).mp3",
  },
  {
    "title": "Open Hearts",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Open Hearts.mp3",
  },
  {
    "title": "Oxytocin",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "Oxytocin.mp3",
  },
  {
    "title": "Pain Killers",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Pain Killers.mp3",
  },
  {
    "title": "Palat - Tera Hero Idhar Hai (From _Main Tera Hero_)",
    "artist": "Arijit Singh",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Palat - Tera Hero Idhar Hai (From _Main Tera Hero_).mp3",
  },
  {
    "title": "Pancake",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Pancake.mp3",
  },
  {
    "title": "peekaboo (feat. azchike)",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "peekaboo (feat. azchike).mp3",
  },
  {
    "title": "Phir Kabhi (From _M.S.Dhoni - The Untold Story_)",
    "artist": "Arijit Singh",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Phir Kabhi (From _M.S.Dhoni - The Untold Story_).mp3",
  },
  {
    "title": "Phir Mohabbat (From _Murder 2_)",
    "artist": "Arijit Singh & Mohammed Irfan",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Phir Mohabbat (From _Murder 2_).mp3",
  },
  {
    "title": "Physical",
    "artist": "Dua Lipa",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Dua+Lipa",
    "path": "Physical.mp3",
  },
  {
    "title": "Pickup",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Pickup.mp3",
  },
  {
    "title": "Plans",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Plans.mp3",
  },
  {
    "title": "Players",
    "artist": "Coi Leray",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Coi+Leray",
    "path": "Players.mp3",
  },
  {
    "title": "Popular (with Playboi Carti & Madonna)",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path":
        "Popular (with Playboi Carti & Madonna) - The Idol Vol. 1 (Music from the HBO Original Series).mp3",
  },
  {
    "title": "Praise The Lord (Da Shine) (feat. Skepta)",
    "artist": "ASAP Rocky",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=ASAP+Rocky",
    "path": "Praise The Lord (Da Shine) (feat. Skepta).mp3",
  },
  {
    "title": "Pray For Me",
    "artist": "The Weeknd & Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "Pray For Me.mp3",
  },
  {
    "title": "PRIDE.",
    "artist": "Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Kendrick+Lamar",
    "path": "PRIDE..mp3",
  },
  {
    "title": "Prisoner (feat. Dua Lipa)",
    "artist": "Miley Cyrus",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Miley+Cyrus",
    "path": "Prisoner (feat. Dua Lipa).mp3",
  },
  {
    "title": "Raabta (From _Agent Vinod_)",
    "artist": "Arijit Singh",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Raabta (From _Agent Vinod_).mp3",
  },
  {
    "title": "Raat Bhar (From _Heropanti_)",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Raat Bhar (From _Heropanti_).mp3",
  },
  {
    "title": "Rahat",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Rahat.mp3",
  },
  {
    "title": "Rap God",
    "artist": "Eminem",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Eminem",
    "path": "Rap God.mp3",
  },
  {
    "title": "Reminder",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "Reminder.mp3",
  },
  {
    "title": "Rich Flex",
    "artist": "Drake & 21 Savage",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Drake",
    "path": "Rich Flex.mp3",
  },
  {
    "title": "Rich Spirit",
    "artist": "Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Kendrick+Lamar",
    "path": "Rich Spirit.mp3",
  },
  {
    "title": "Ride It",
    "artist": "Jay Sean",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Jay+Sean",
    "path": "Ride It.mp3",
  },
  {
    "title": "Riding Alone",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Riding Alone.mp3",
  },
  {
    "title": "rockstar (feat. 21 Savage)",
    "artist": "Post Malone",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Post+Malone",
    "path": "rockstar (feat. 21 Savage).mp3",
  },
  {
    "title": "Sacrifice",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "Sacrifice.mp3",
  },
  {
    "title": "Sanam Re (From _Sanam Re_)",
    "artist": "Arijit Singh & Mithoon",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Sanam Re (From _Sanam Re_).mp3",
  },
  {
    "title": "Save Your Tears",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "Save Your Tears.mp3",
  },
  {
    "title": "Say So",
    "artist": "Doja Cat",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Doja+Cat",
    "path": "Say So.mp3",
  },
  {
    "title": "Scared to Be Lonely",
    "artist": "Martin Garrix & Dua Lipa",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Dua+Lipa",
    "path": "Scared to Be Lonely.mp3",
  },
  {
    "title": "Shaamein",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Shaamein.mp3",
  },
  {
    "title": "Shanivaar Raati (From _Main Tera Hero_)",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Shanivaar Raati (From _Main Tera Hero_).mp3",
  },
  {
    "title": "Shivers",
    "artist": "Ed Sheeran",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Ed+Sheeran",
    "path": "Shivers.mp3",
  },
  {
    "title": "SICKO MODE",
    "artist": "Travis Scott",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Travis+Scott",
    "path": "SICKO MODE.mp3",
  },
  {
    "title": "Sidewalks",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "Sidewalks.mp3",
  },
  {
    "title": "Sike",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Sike.mp3",
  },
  {
    "title": "Six Feet Under",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "Six Feet Under.mp3",
  },
  {
    "title": "SKINNY",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "SKINNY.mp3",
  },
  {
    "title": "Sober",
    "artist": "Childish Gambino",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Childish+Gambino",
    "path": "Sober.mp3",
  },
  {
    "title": "Soch Na Sake (From _Airlift_)",
    "artist": "Arijit Singh",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Soch Na Sake (From _Airlift_).mp3",
  },
  {
    "title": "Sooraj Dooba Hain (From _Roy_)",
    "artist": "Arijit Singh & Aditi Singh Sharma",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Sooraj Dooba Hain (From _Roy_).mp3",
  },
  {
    "title": "squabble up",
    "artist": "Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Kendrick+Lamar",
    "path": "squabble up.mp3",
  },
  {
    "title": "Starboy",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "Starboy.mp3",
  },
  {
    "title": "Stargirl Interlude",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "Stargirl Interlude.mp3",
  },
  {
    "title": "Stay Ready (What A Life)",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Stay Ready (What A Life).mp3",
  },
  {
    "title": "Stay Schemin",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Stay Schemin.mp3",
  },
  {
    "title": "Sucker",
    "artist": "Jonas Brothers",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Jonas+Brothers",
    "path": "Sucker.mp3",
  },
  {
    "title": "Suno- Na Sangemarmar (From _Youngistaan_)",
    "artist": "Arijit Singh",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Suno- Na Sangemarmar (From _Youngistaan_).mp3",
  },
  {
    "title": "Sure Thing",
    "artist": "Miguel",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Miguel",
    "path": "Sure Thing.mp3",
  },
  {
    "title": "Sweetest Pie",
    "artist": "Megan Thee Stallion & Dua Lipa",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Dua+Lipa",
    "path": "Sweetest Pie.mp3",
  },
  {
    "title": "Swimming Pools (Drank)",
    "artist": "Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Kendrick+Lamar",
    "path": "Swimming Pools (Drank).mp3",
  },
  {
    "title": "S\u00e3o Paulo (feat. Anitta)",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "S\u00e3o Paulo (feat. Anitta).mp3",
  },
  {
    "title": "Take My Breath",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "Take My Breath.mp3",
  },
  {
    "title": "The 30th",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "The 30th.mp3",
  },
  {
    "title": "THE DINER",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "THE DINER.mp3",
  },
  {
    "title": "The Greatest (feat. Kendrick Lamar)",
    "artist": "Sia",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Sia",
    "path": "The Greatest (feat. Kendrick Lamar).mp3",
  },
  {
    "title": "THE GREATEST",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "THE GREATEST.mp3",
  },
  {
    "title": "The Hills",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "The Hills.mp3",
  },
  {
    "title": "The Next Episode",
    "artist": "Dr. Dre",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Dr.+Dre",
    "path": "The Next Episode.mp3",
  },
  {
    "title": "The Party & The After Party",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "The Party & The After Party.mp3",
  },
  {
    "title": "Therefore I Am",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "Therefore I Am.mp3",
  },
  {
    "title": "Timeless (feat. Playboi Carti & Doechii) - Remix",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "Timeless (feat. Playboi Carti & Doechii) - Remix.mp3",
  },
  {
    "title": "Too Good",
    "artist": "Drake",
    "image": "https://i.ibb.co/4gjhTrKm/download-5.jpg",
    "path": "Too Good.mp3",
  },
  {
    "title": "Tose Naina (From _Mickey Virus_)",
    "artist": "Arijit Singh",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Tose Naina (From _Mickey Virus_).mp3",
  },
  {
    "title": "Training Season",
    "artist": "Dua Lipa",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Dua+Lipa",
    "path": "Training Season.mp3",
  },
  {
    "title": "Trap Queen",
    "artist": "Fetty Wap",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Fetty+Wap",
    "path": "Trap Queen.mp3",
  },
  {
    "title": "Tum Hi Ho (From _Aashiqui 2_)",
    "artist": "Arijit Singh",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Tum Hi Ho (From _Aashiqui 2_).mp3",
  },
  {
    "title": "tv off (feat. lefty gunplay)",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "tv off (feat. lefty gunplay).mp3",
  },
  {
    "title": "TV",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "TV.mp3",
  },
  {
    "title": "UFO",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "UFO.mp3",
  },
  {
    "title": "United In Grief",
    "artist": "Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Kendrick+Lamar",
    "path": "United In Grief.mp3",
  },
  {
    "title": "Up",
    "artist": "Cardi B",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Cardi+B",
    "path": "Up.mp3",
  },
  {
    "title": "Venom",
    "artist": "Eminem",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Eminem",
    "path": "Venom - Music From The Motion Picture.mp3",
  },
  {
    "title": "Video Games",
    "artist": "Lana Del Rey",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Lana+Del+Rey",
    "path": "Video Games.mp3",
  },
  {
    "title": "Wajah",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Wajah.mp3",
  },
  {
    "title": "WAP (feat. Megan Thee Stallion)",
    "artist": "Cardi B",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Cardi+B",
    "path": "WAP (feat. Megan Thee Stallion).mp3",
  },
  {
    "title": "Wat Wat Wat (From _Tamasha_)",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Wat Wat Wat (From _Tamasha_).mp3",
  },
  {
    "title": "Wat's Wrong (feat. Zacari & Kendrick Lamar)",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Wat's Wrong (feat. Zacari & Kendrick Lamar).mp3",
  },
  {
    "title": "watch",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "watch.mp3",
  },
  {
    "title": "Watermelon Sugar",
    "artist": "Harry Styles",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Harry+Styles",
    "path": "Watermelon Sugar.mp3",
  },
  {
    "title": "We Own It (Fast & Furious)",
    "artist": "2 Chainz & Wiz Khalifa",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=2+Chainz",
    "path": "We Own It (Fast & Furious).mp3",
  },
  {
    "title": "We Still Don't Trust You",
    "artist": "Future & Metro Boomin",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Future",
    "path": "We Still Don't Trust You.mp3",
  },
  {
    "title": "Wesley's Theory",
    "artist": "Kendrick Lamar",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Kendrick+Lamar",
    "path": "Wesley's Theory.mp3",
  },
  {
    "title": "when the party's over",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "when the party's over.mp3",
  },
  {
    "title": "Where Are You Now",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "Where Are You Now.mp3",
  },
  {
    "title": "WILDFLOWER",
    "artist": "Unknown Artist",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Music",
    "path": "WILDFLOWER.mp3",
  },
  {
    "title": "wish you were gay",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "wish you were gay.mp3",
  },
  {
    "title": "Work Out",
    "artist": "J. Cole",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=J.+Cole",
    "path": "Work Out.mp3",
  },
  {
    "title": "Yaad Hai Na (From _Raaz Reboot_)",
    "artist": "Arijit Singh",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Arijit+Singh",
    "path": "Yaad Hai Na (From _Raaz Reboot_).mp3",
  },
  {
    "title": "You Right",
    "artist": "Doja Cat & The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Doja+Cat",
    "path": "You Right.mp3",
  },
  {
    "title": "you should see me in a crown",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "you should see me in a crown.mp3",
  },
  {
    "title": "You",
    "artist": "The Weeknd",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=The+Weeknd",
    "path": "You.mp3",
  },
  {
    "title": "Youngblood",
    "artist": "5 Seconds of Summer",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=5+Seconds",
    "path": "Youngblood.mp3",
  },
  {
    "title": "Your Power",
    "artist": "Billie Eilish",
    "image": "https://placehold.co/200x200/4A1F47/ffffff?text=Billie+Eilish",
    "path": "Your Power.mp3",
  },
  {
    "title": "\u0928alla Freestyle",
    "artist": "Seedhe Maut",
    "image": "https://i.ibb.co/xqR41Stf/download-10.jpg",
    "path": "\u0928alla Freestyle.mp3",
  },
];

// --- ADD THE NEW ARTIST LIST BELOW YOUR SONGS LIST ---

final List<Map<String, dynamic>> allArtists = [
  {
    'name': 'The Weeknd',
    'image': 'https://i.scdn.co/image/ab67616100005174214f3cf1cbe7139c1e26ffbb',
    'headerImage':
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfzFjmeosiQLmwOiwaJSSeSeq4J9liwdOKpQ&s',
    'followers': '85.1M',
    'albums': [
      {
        'title': 'After Hours',
        'year': '2020',
        'image':
            'https://i.scdn.co/image/ab67616d0000b2734718e2b124f79258be7bc452',
      },
      {
        'title': 'Starboy',
        'year': '2016',
        'image':
            'https://i.scdn.co/image/ab67616d0000b2734718e2b124f79258be7bc452',
      },
    ],
  },
  {
    'name': 'Taylor Swift',
    'image': 'https://i.scdn.co/image/ab67616100005174e672b5f553298dcdccb0e676',
    'headerImage':
        'https://i.pinimg.com/originals/39/75/0b/39750b209d434241c62cc3ede7d36e83.jpg',
    'followers': '89.5M',
    'albums': [
      {
        'title': 'Midnights',
        'year': '2022',
        'image':
            'https://i.scdn.co/image/ab67616d0000b273bb54dde68cd23e2a268ae0f5',
      },
      {
        'title': '1989',
        'year': '2014',
        'image':
            'https://tse2.mm.bing.net/th/id/OIP.DXCdphMI9MKKgYd4F85MgQAAAA?pid=Api&P=0&h=180',
      },
    ],
  },
  {
    'name': 'Billie Eilish',
    'image':
        'https://tse4.mm.bing.net/th/id/OIP.f9AUDB4ynQ4AHnVR3AXGHwHaEs?pid=Api&P=0&h=180',
    'headerImage':
        'https://www.baltana.com/files/wallpapers-23/Billie-Eilish-Wallpaper-3000x1651-59795.jpg',
    'followers': '98.2M',
    'albums': [
      {
        'title': 'BIRDS OF A FEATHER',
        'year': '2020',
        'image':
            'https://tse4.mm.bing.net/th/id/OIP.4WsdifWr7nxNZi8lq_vYYwHaHa?pid=Api&P=0&h=180',
      },
      {
        'title': 'Starboy',
        'year': '2016',
        'image':
            'https://i.scdn.co/image/ab67616d0000b2734718e2b124f79258be7bc452',
      },
    ],
  },

  {
    'name': 'Seedhe Maut',
    'image':
        'https://i.pinimg.com/1200x/10/c6/a7/10c6a7cfb88a6c037cb2339d5ed68b5c.jpg',
    'headerImage':
        'https://i.pinimg.com/736x/b3/93/04/b393044feab74a2ccb922d3e8f3f8159.jpg',
    'followers': '8.2M',
    'albums': [
      {
        'title': 'DL91 FM',
        'year': '2025',
        'image':
            'https://tse4.mm.bing.net/th/id/OIP.Pxv-_7A_I2nkQjbpCSfEMAHaHa?pid=Api&P=0&h=180',
      },
    ],
  },

  {
    'name': 'Arijit Singh',
    'image':
        'https://tse1.mm.bing.net/th/id/OIP.1M_2_mLd3GcOJ84t4tP4VQHaHa?pid=Api&P=0&h=180',
    'headerImage':
        'https://www.bizasialive.com/wp-content/uploads/2022/05/arijit001.jpg',
    'followers': '8.2M',
    'albums': [
      {
        'title': 'Suddh Desi Song',
        'year': '2019',
        'image':
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjgTz61upYkUO_C38Pf5GnZ81YZy_ofCQgNLzhSacIMju-OnXZofy68WK0QLYWvzf_u7k&usqp=CAU',
      },
      {
        'title': 'Arijit Hits',
        'year': '2016',
        'image':
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRinZa1YUdqX5Xee2kK9QIIF2cZsdJgJPAzUqCvz4aY9mp60BhnAbpJKhcflXMvViB35bs&usqp=CAU',
      },
    ],
  },

  {
    'name': 'Drake',
    'image': 'https://i.ibb.co/6Rg1bcRM/download.jpg',
    'headerImage':
        'https://www.etonline.com/sites/default/files/styles/video_1920x1080/public/images/2023-10/ETD_SHOWCLIP_A06%20DRAKE_100623_VIDPIC.jpg?h=d1cb525d&width=1280&height=720',
    'followers': '8.2M',
    'albums': [
      {
        'title': 'Scorpion',
        'year': '20218',
        'image': 'https://i.ibb.co/Dg4h3skr/download-1.jpg',
      },
      {
        'title': 'For All the Dogs',
        'year': '2023',
        'image': 'https://i.ibb.co/HDDDvr6m/download-2.jpg',
      },
    ],
  },

  {
    'name': 'Kendrick Lamar',
    'image': 'https://4kwallpapers.com/images/walls/thumbs_2t/21246.jpg',
    'headerImage': 'https://wallpapercave.com/wp/wp2522986.jpg',
    'followers': '8.2M',
    'albums': [
      {
        'title': 'Section.80',
        'year': '2011',
        'image': 'https://i.ibb.co/Dfw8SJ1C/download-3.jpg',
      },
      {
        'title': 'GNX',
        'year': '2016',
        'image': 'https://i.ibb.co/M5Wpb68s/download-4.jpg',
      },
    ],
  },

  {
    'name': 'Talha Anjum',
    'image':
        'https://rollingstoneindia.com/wp-content/uploads/2024/12/Talha-Anjum-white-scaled-e1735381108282.jpeg',
    'headerImage':
        'https://www.bolnews.com/wp-content/uploads/2024/12/FotoJet-43-1-635x430.jpg',
    'followers': '8.2M',
    'albums': [
      {
        'title': 'Open Letter',
        'year': '2023',
        'image': 'https://i.ibb.co/6RrhKqfG/download-6.jpg',
      },
      {
        'title': 'My Terreble Mind',
        'year': '2024',
        'image': 'https://i.ibb.co/JwLDryP6/download-7.jpg',
      },
    ],
  },

  {
    'name': 'Talha Yumus',
    'image': 'https://wikibio.in/wp-content/uploads/2022/02/Talhah-Yunus.jpg',
    'headerImage': 'https://i.ytimg.com/vi/_94OPP9ShkY/maxresdefault.jpg',
    'followers': '8.2M',
    'albums': [
      {
        'title': 'Shikwa Side A',
        'year': '2025',
        'image': 'https://i.ibb.co/cjb7FgZ/download-8.jpg',
      },
      {
        'title': 'Shikwa Side B',
        'year': '2024',
        'image': 'https://i.ibb.co/Vc5LtZWZ/download-9.jpg',
      },
    ],
  },
  // You can add more artists here
];
